---
- hosts: 4linux
  become: yes
  vars_files:
    - ~/Documents/project_learning/projects/4linux/ansible/vars/vars.yml

  tasks:
    - name: "Rodando o equivalente de apt-get update"
      apt: 
        update_cache: yes

    - name: Instalando pacotes do NGINX e dependencias do Docker.
      apt:
        name: ["nginx", "apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present

    - name: Copiando arquivos de configuração (Nginx e Docker Compose).
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
        - { src: "{{ path_conf_nginx_app1 }}", dest: '/etc/nginx/sites-available/app1.dexter.com.br.conf' }
        - { src: "{{ path_conf_nginx_app2 }}", dest: '/etc/nginx/sites-available/app2.dexter.com.br.conf' }
        - { src: "{{ path_conf_nginx_app3 }}", dest: '/etc/nginx/sites-available/app3.dexter.com.br.conf' }
        - { src: "{{ path_dockercompose_file }}", dest: '/tmp/docker-compose.yml' }

    - name: Criando link simbolico para app*.conf
      command: "{{ item }}"
      with_items:
        - ln -s /etc/nginx/sites-available/app1.dexter.com.br.conf /etc/nginx/sites-enabled/app1.dexter.com.br.conf
        - ln -s /etc/nginx/sites-available/app2.dexter.com.br.conf /etc/nginx/sites-enabled/app2.dexter.com.br.conf
        - ln -s /etc/nginx/sites-available/app3.dexter.com.br.conf /etc/nginx/sites-enabled/app3.dexter.com.br.conf

    - name: Removendo arquivo default do NGINX
      command: rm -f /etc/nginx/sites-available/default

    - name: Adicionando apontamento no arquivo hosts.
      command: "{{ item }}"
      with_items:
        - echo "192.168.33.101 app1.dexter.com.br" >> /etc/hosts
        - echo "192.168.33.101 app2.dexter.com.br" >> /etc/hosts
        - echo "192.168.33.101 app3.dexter.com.br" >> /etc/hosts

    - name: Instalando o Docker
      script: "{{ path_install_docker }}" 

    - name: Instalar Docker-Compose.
      script: "{{ path_install_docker_compose }}"

    - name: Rodando Docker-Compose.
      script: "{{ path_dockercompose_script }}"
      
    - name: Reiniciando servico do NGINX
      systemd:
        state: restarted
        name: nginx

    - name: Instalando python-pip
      apt: 
        name: python-pip
        state: present

    - name: Instalando lib testinfra
      shell: pip install testinfra

    - name: Copiando script python para testar a infraestrutura.
      copy: 
        src: "{{ path_script_python }}"
        dest: /tmp/test_infra.py

    - name: Rodando py.test
      command:  py.test -v  /tmp/test_infra.py
      register: infra

    - debug: var=infra.stdout_lines